 tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                "primary-fixed-dim": "#00e0bb",
                "secondary-container": "#3e484e",
                "surface-container": "#122131",
                "surface-bright": "#2c3a4c",
                "surface-dim": "#051424",
                "surface-container-highest": "#273647",
                "on-tertiary-fixed-variant": "#3e484f",
                "on-primary-fixed-variant": "#005142",
                "on-secondary": "#283237",
                "on-secondary-fixed": "#131d22",
                "outline": "#83948e",
                "on-primary-fixed": "#002019",
                "on-background": "#d4e4fa",
                "on-error-container": "#ffdad6",
                "on-tertiary-fixed": "#131d23",
                "tertiary": "#ffffff",
                "on-secondary-fixed-variant": "#3e484e",
                "surface": "#051424",
                "error-container": "#93000a",
                "on-surface": "#d4e4fa",
                "inverse-primary": "#006b58",
                "on-surface-variant": "#b9cac3",
                "surface-variant": "#273647",
                "inverse-surface": "#d4e4fa",
                "surface-tint": "#00e0bb",
                "secondary": "#bdc8cf",
                "primary": "#ffffff",
                "surface-container-low": "#0d1c2d",
                "error": "#ffb4ab",
                "on-primary": "#00382d",
                "on-primary-container": "#00725e",
                "on-tertiary-container": "#5b666d",
                "secondary-fixed": "#dae4eb",
                "primary-fixed": "#00ffd5",
                "primary-container": "#00ffd5",
                "surface-container-lowest": "#010f1f",
                "outline-variant": "#3a4a45",
                "tertiary-fixed": "#d9e4ec",
                "on-error": "#690005",
                "secondary-fixed-dim": "#bdc8cf",
                "on-tertiary": "#283238",
                "background": "#051424",
                "tertiary-container": "#d9e4ec",
                "tertiary-fixed-dim": "#bdc8d0",
                "surface-container-high": "#1c2b3c",
                "on-secondary-container": "#acb7bd",
                "inverse-on-surface": "#233143"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "margin-desktop": "64px",
                "container-max": "1280px",
                "gutter": "24px",
                "unit": "4px",
                "margin-mobile": "16px"
            },
            "fontFamily": {
                "body-lg": ["Inter"],
                "label-caps": ["Inter"],
                "headline-lg": ["Montserrat"],
                "headline-sm": ["Montserrat"],
                "headline-md": ["Montserrat"],
                "body-md": ["Inter"],
                "headline-lg-mobile": ["Montserrat"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "label-caps": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.1em", "fontWeight": "500"}],
                "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-sm": ["18px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-lg-mobile": ["26px", {"lineHeight": "1.2", "fontWeight": "700"}]
            }
          },
        },
      }